# Site settings
title: Android Developer, Blogger
email: kmshack@naver.com
description: kmshack
baseurl: "" # the subpath of your site, e.g. /blog
url: "kmshack.github.io" # the base hostname & protocol for your site

# Identity
your-name: Minsoo Kim
your-title: Think Simple

# Social settings
500px_url: 
facebook_url: https://facebook.com/kmshack
github_url: https://github.com/kmshack
gitlab_url: 
googleplus_url: https://plus.google.com/+KMSHACK
instagram_url: 
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/kmshack_kr

# Build settings
markdown: kramdown